---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Defining Commodity Currencies: A Formal Approach**

A formal definition for a commodity currency remains surprisingly elusive to this day ([A. Jeanneret, V. Sokolovski, 2024](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4564504)). There is a lack of a consistent definition/procedure that can be utilized to draw a conclusion. In the research paper titled *Looking Under the Hood of Commodity Currency Predictability* by Dr. Alexandre Jeanneret and Dr. Valeri Sokolovski, a formal definition has been proposed as:

*"[A commodity currency is] a country's currency that demonstrates a statistically and economically meaningful contemporaneous exposure to its commodity export/import prices, after accounting for the influence of the US dollar."*

### **Statistical and Economically Meaningful Exposures**

To classify which exporters have such exposures, researchers used a market-based approach utilizing a multivariate linear regression, as follows:

$$
\Delta s_{i,t} = \alpha_i + \beta_i \Delta CEP_{i,t} + \gamma_i DOL_t + \varepsilon_{i,t}
$$

Where:

-   $\Delta s_{i,t}$ is the **log change in the exchange rate** of currency $i$ (USD per unit of foreign currency).
-   $\Delta CEP_{i,t}$ represents the **log change in the country-specific commodity price index**, calculated using **export/import-weighted changes in international commodity prices**.
-   $DOL_t$ is the **dollar factor**, capturing the **average movement of exchange rates relative to the U.S. dollar**.
-   $\beta_i$ is the **commodity price beta**, which measures how much the exchange rate moves in response to changes in commodity prices.
-   **A statistically significant** $\beta_i$ **indicates a meaningful exposure of the currency to commodity prices**.

To **control for the influence of the U.S. dollar**, the researchers regression includes $DOL_t$ to ensure that movements in commodity prices are not merely reflecting broad USD fluctuations using the researchers use the method outlined by [Verdekhan,2018](https://econpapers.repec.org/article/blajfinan/v_3a73_3ay_3a2018_3ai_3a1_3ap_3a375-418.htm).

For the purposes of demonstration a crude DOL is used in our model and is defined by:

$$
\text{DOL}_{t+1} = \frac{1}{N} \sum_{i=1}^{N} \Delta s_{t+1,i}
$$

Where:

-   $\text{DOL}_{t+1}$ is the Dollar Risk Factor at time $t+1$,
-   $N$ is the number of currencies,
-   $\Delta s_{t+1,i}$ is the change in the exchange rate for the $i$-th currency at time $t+1$.

